=begin
#PowerDNS Authoritative HTTP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.13

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for PowerDNS::ConfigApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ConfigApi' do
  before do
    # run before each test
    @instance = PowerDNS::ConfigApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConfigApi' do
    it 'should create an instance of ConfigApi' do
      expect(@instance).to be_instance_of(PowerDNS::ConfigApi)
    end
  end

  # unit tests for get_config
  # Returns all ConfigSettings for a single server
  # @param server_id The id of the server to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Array<ConfigSetting>]
  describe 'get_config test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_config_setting
  # Returns a specific ConfigSetting for a single server
  # NOT IMPLEMENTED
  # @param server_id The id of the server to retrieve
  # @param config_setting_name The name of the setting to retrieve
  # @param [Hash] opts the optional parameters
  # @return [ConfigSetting]
  describe 'get_config_setting test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
