=begin
#PowerDNS Authoritative HTTP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.13

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'powerdns/api_client'
require 'powerdns/api_error'
require 'powerdns/version'
require 'powerdns/configuration'

# Models
require 'powerdns/models/base_statistic_item'
require 'powerdns/models/comment'
require 'powerdns/models/config_setting'
require 'powerdns/models/cryptokey'
require 'powerdns/models/map_statistic_item_value'
require 'powerdns/models/metadata'
require 'powerdns/models/rr_set'
require 'powerdns/models/record'
require 'powerdns/models/search_result'
require 'powerdns/models/search_result_comment'
require 'powerdns/models/search_result_record'
require 'powerdns/models/search_result_zone'
require 'powerdns/models/search_results'
require 'powerdns/models/server'
require 'powerdns/models/servers'
require 'powerdns/models/zone'
require 'powerdns/models/zones'
require 'powerdns/models/map_statistic_item'
require 'powerdns/models/ring_statistic_item'
require 'powerdns/models/statistic_item'

# APIs
require 'powerdns/api/config_api'
require 'powerdns/api/search_api'
require 'powerdns/api/servers_api'
require 'powerdns/api/stats_api'
require 'powerdns/api/zonecryptokey_api'
require 'powerdns/api/zonemetadata_api'
require 'powerdns/api/zones_api'

module PowerDNS
  class << self
    # Customize default settings for the SDK using block.
    #   PowerDNS.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
